# Generated by Django 4.0.1 on 2023-11-03 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_productsatus_alter_user_photo_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productsatus',
            options={'verbose_name': 'Product status', 'verbose_name_plural': 'Product Statuses'},
        ),
        migrations.AlterField(
            model_name='products',
            name='product_status_id',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.productsatus'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='uploads/user-photo/default.jpg', upload_to='uploads/<function user_directory_path at 0x00000167DB07FCE0>'),
        ),
    ]
