# Generated by Django 4.0.1 on 2023-11-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_orderstatus_alter_user_photo_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='uploads/user-photo/default.jpg', upload_to='uploads/<function user_directory_path at 0x00000200A915FA60>'),
        ),
    ]
