# Generated by Django 4.0.1 on 2023-11-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_product_id_orders_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='product',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='uploads/user-photo/default.jpg', upload_to='uploads/<function user_directory_path at 0x0000020B7B39FA60>'),
        ),
    ]
