# Generated by Django 4.0.1 on 2023-11-17 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_product_orders_product_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_discount', models.FloatField(default=0)),
                ('date_add_limit', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Settings',
                'verbose_name_plural': 'Settings',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='uploads/user-photo/default.jpg', upload_to='uploads/<function user_directory_path at 0x000001D9CD82FCE0>'),
        ),
    ]
